import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/app/misComponentes/Header"
import Footer from "@/app/misComponentes/Footer"
import HeaderMobile from "./misComponentes/HeaderMobile"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={`${inter.className} bg-black text-white min-h-screen antialiased flex flex-col`}>
        <div className="hidden md:block">
          <Header />
        </div>
        <div className="block md:hidden">
          <HeaderMobile />
        </div>
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
